# Site
repository: dyparkkk/dyparkkk.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박도영  
title: Java 백엔드 엔지니어 신입
email: dkdlel1z@naver.com
website: https://velog.io/@dyparkkk

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dyparkkk

# About Section
# about_title: About Me
about_profile_image: images/pic06.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 백엔드 개발자를 목표로 하고 있습니다.  
  새로운 기술을 학습에 그치지 않고 적용해보려고 끊임없이 시도하고 있습니다.  
  개인의 성장도 중요하지만 <mark>회사와 팀을 위해</mark> 일하는 것이 프로라고 생각합니다.  
  <mark>리펙토링</mark>을 통한 직관적이고 이해하기 쉬운 코드 작성에 관심이 많습니다.  
  견고한 코드 작성을 위해 <mark>테스트 주도 개발</mark>을 시도하고 있습니다.  


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 맘카페 모바일 커뮤니티
        link: https://github.com/dyparkkk/woowa-backend
        caption: 2022.03 ~ 진행중
        description: | # this will include new lines to allow paragraphs
          - 5명으로 이루어진 팀에서 <mark>팀장</mark>을 맡아서 기획, 일정관리, 기록 등의 역할을 맡음
          - [API 문서화](https://github.com/dyparkkk/woowa-backend/wiki)를 담당
          - 회원관리, 로그인 개발
          
      - layout: left
        title: JWT Demo
        link: github.com/dyparkkk/jwt-spring-security-demo
        caption: 2022.02 ~ 2022.02
        description: | # this will include new lines to allow paragraphs
          - JWT를 직접 구현해보고 싶어서 개발
          - Spring Security, Spring Data Redis 등 관심있던 프레임워크 적용
          - [코드 리펙토링](https://velog.io/@dyparkkk/series/securityjwtredis) 및 성능 테스트

      - layout: left
        title: 위치 기반 모바일 채팅 서비스
        link: https://github.com/dyparkkk/date_app_spring
        caption: 2021.07 ~ 2021.11 (졸업 프로젝트)
        description: | # this will include new lines to allow paragraphs
          - Stomp 프로토콜을 사용한 실시간 채팅 서비스 개발
          - 투표, 평가하기 기능
          - [소개 영상](https://www.youtube.com/watch?v=O-puhurUpMU) 제작

  - title: Self-development
    layout: list
    content:
      - layout: left
        title: Today I Learned
        link: https://github.com/dyparkkk/TIL
        description: | 
          - 공부한 것 기록
          - 양질의 서적에서 리소스를 얻음
      - layout: left
        title: blog
        link: https://velog.io/@dyparkkk
        quote: > 
          개발의 과정을 기록
        description: | 
          - 어떤 부분을 신경써서 개발 했는지, 개선하려고 했는지
    
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        description: | 
          - Java
          - Spring Boot, Spring MVC, Spring Security, Spring data JPA/Redis
          - JPA, Gradle
          - IntelliJ, Visual Studio Code
      - layout: left
        title: DevOps
        description: |
          - MariaDB
          - AWS EC2, RDS

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 홍익대학교
        caption: 2016.03 - 2022.02 졸
        sub_title: 컴퓨터공학 전공

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     작성중

    # Sample
  # - title:  # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
